# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Platinum Welding and Fabrication
email: platinumweldinginc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Make or repair bumpers,Deer, Moose, and Front Bumper,Repair all kinds of straights,Assembly
  ,Sheet metal work,Truck and Trailer repair,Trailer repair,Diesel tank repair, Diesel tank locks,
  cascadia bumper ,frightliner bumper ,truck bumper brampton,toronto truck bumper,oakville truck bumper ,
  volvo bumper,brampton bumper,cheap truck bumper ,solid truck bumper,aluminum truck bumper ,aluminum bumper ,steel bumper,deer bumper,moose bumper 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
email: platinumweldinginc@gmail.com
facebook_username: platinumweldinginc
twitter_username: platinumweldinginc
github_username: platinumweldinginc
address: 20 Melanie Dr Unit 6 ,Brampton, ON L6T4K8 Canada
  # Feel free to add more lines here 
telephone: +1 (647) 786 2277
copyright:

# API settings
google_api_key: AIzaSyBsydjYEt52DkXuQd0-zXtUnmy2O1XHdJc